=== Lokhy87/DAW.FLORIDA/LMSGI - LENGUAJES DE MARCAS Y SISTEMAS DE GESTION DE LA INFORMACION/ACTIVIDADES/alberto_bolta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="MesType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Enero"/>
        <xs:enumeration value="Febrero"/>
        <xs:enumeration value="Marzo"/>
        <xs:enumeration value="Abril"/>
        <xs:enumeration value="Mayo"/>
        <xs:enumeration value="Junio"/>
        <xs:enumeration value="Julio"/>
        <xs:enumeration value="Agosto"/>
        <xs:enumeration value="Septiembre"/>
        <xs:enumeration value="Octubre"/>
        <xs:enumeration value="Noviembre"/>
        <xs:enumeration value="Diciembre"/>
    </xs:restriction>
</xs:simpleType>

<xs:element name="curriculum">
    <xs:complexType>
        <xs:sequence>

            <xs:element name="datos_personales">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="apellidos" type="xs:string"/>
                        <xs:element name="fecha_nacimiento">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="dia">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="1"/>
                                                <xs:maxInclusive value="31"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="mes">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="1"/>
                                                <xs:maxInclusive value="12"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>    
                                    <xs:element name="año">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="1900"/>
                                                <xs:maxInclusive value="2099"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>    
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>    
                        <xs:element name="lugar_nacimiento" type="xs:string"/>
                        <xs:element name="nacionalidad" type="xs:string"/>
                        <xs:element name="dni">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\d{8}[A-Za-z]"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="foto"/>
                </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="datos_direccion_contacto">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="domicilio">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="tipo_via" type="xs:string"/>
                                    <xs:element name="nombre_via" type="xs:string"/>
                                    <xs:element name="numero" type="xs:positiveInteger"/>
                                    <xs:element name="piso" type="xs:string"/>
                                    <xs:element name="puerta" type="xs:positiveInteger"/>
                                    <xs:element name="codigo_postal">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="10000"/>
                                                <xs:maxInclusive value="99999"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>    
                                    <xs:element name="pais" type="xs:string"/>
                                    <xs:element name="provincia" type="xs:string"/>
                                    <xs:element name="municipio" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="correo_electronico">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="email" minOccurs="2" maxOccurs="unbounded"/>                       
                                </xs:sequence>
                                <xs:attribute name="uso" type="xs:string"/>
                            </xs:complexType>                       
                        </xs:element>
                        <xs:element name="telefonos" >
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="telefono" minOccurs="1" maxOccurs="unbounded"/>                                                           
                                </xs:sequence>
                                <xs:attribute name="tipo" type="xs:string"/>  
                            </xs:complexType>                       
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="otros_datos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="pagina_web" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element name="redes_sociales"/>
                    </xs:sequence>
                    <xs:attribute name="nombre" type="xs:string"/>
                </xs:complexType>
            </xs:element>

            <xs:element name="formacion">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="titulacion" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre"/>
                                    <xs:element name="centro"/>
                                    <xs:element name="fecha_inicio">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="mes" type="MesType"/>
                                                <xs:element name="año">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1000"/>
                                                            <xs:maxInclusive value="9999"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>    
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="fecha_finalizacion">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="mes" type="MesType"/>   
                                                <xs:element name="año">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1000"/>
                                                            <xs:maxInclusive value="9999"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>    
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>    
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="idiomas">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="idioma" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre"/>
                                    <xs:element name="expresion_oral">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Alto"/>
                                                <xs:enumeration value="Medio"/>
                                                <xs:enumeration value="Bajo"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>    
                                    <xs:element name="comprension_oral">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Alto"/>
                                                <xs:enumeration value="Medio"/>
                                                <xs:enumeration value="Bajo"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                    <xs:element name="expresion_escrita">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Alto"/>
                                                <xs:enumeration value="Medio"/>
                                                <xs:enumeration value="Bajo"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="materno" type="xs:boolean" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>           
            </xs:element>

            <xs:element name="experiencia_laboral">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="empresa" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre"/>
                                    <xs:element name="puesto"/>
                                    <xs:element name="inicio_contrato">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="dia">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1"/>
                                                            <xs:maxInclusive value="31"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                                <xs:element name="mes" type="MesType"/>
                                                <xs:element name="año">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1900"/>
                                                            <xs:maxInclusive value="2099"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="final_contrato" minOccurs="0" maxOccurs="1">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="dia" nillable="true"> 
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:pattern value="[0-9]*"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                                <xs:element name="mes" nillable="true" type="MesType"/>
                                                <xs:element name="año" nillable="true">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1900"/>
                                                            <xs:maxInclusive value="2099"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="competencias">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="competencia" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre"/>
                                    <xs:element name="nivel">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:minInclusive value="1"/>
                                                <xs:maxInclusive value="5"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>            
            </xs:element>

            <xs:element name="datos_adicionales">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="aficiones" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="disponibilidad_viajar">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Si"/>
                                    <xs:enumeration value="No"/>                              
                                </xs:restriction>
                            </xs:simpleType>                            
                        </xs:element>
                        <xs:element name="vehiculo_propio">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Si"/>
                                    <xs:enumeration value="No"/>                              
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="permisos">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="nombre" minOccurs="1" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:attribute name="licencia" type="xs:string" use="required"/>
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>            
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>  

        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Lokhy87/DAW.FLORIDA/LMSGI - LENGUAJES DE MARCAS Y SISTEMAS DE GESTION DE LA INFORMACION/ACTIVIDADES/alberto_bolta.xml
<?xml version="1.0" encoding="UTF-8"?>
<curriculum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="alberto_bolta.xsd">

    <datos_personales>
        <nombre>Alberto</nombre>
        <apellidos>Bolta Sanmateu</apellidos>
        <fecha_nacimiento>
            <dia>08</dia>
            <mes>01</mes>
            <año>1987</año>
        </fecha_nacimiento>
        <lugar_nacimiento>Gandia</lugar_nacimiento>
        <nacionalidad>España</nacionalidad>
        <dni>53384069B</dni>
        <foto>C:/Users/admin/OneDrive/Escritorio/FP/LMSGI - LENGUAJES DE MARCAS Y SISTEMAS DE GESTION DE LA INFORMACION/fotocarnet.png</foto>
    </datos_personales>

    <datos_direccion_contacto>
        <domicilio>
            <tipo_via>Plaza</tipo_via>
            <nombre_via>Ciudad de la Lisa</nombre_via>
            <numero>8</numero>
            <piso>Entresuelo</piso>
            <puerta>1</puerta>
            <codigo_postal>46920</codigo_postal>
            <pais>España</pais>
            <provincia>Valencia</provincia>
            <municipio>Mislata</municipio>
        </domicilio>
        <correo_electronico>
            <email uso = 'personal'>a.bolta@gmail.com</email>
            <email uso = 'profesional'>a.bolta@alfatrainers.com</email>
        </correo_electronico>
        <telefonos>
            <telefono tipo = 'movil'>622363288</telefono>
            <telefono tipo = 'fijo'></telefono>
        </telefonos>
    </datos_direccion_contacto>

    <otros_datos>
        <pagina_web></pagina_web>
        <redes_sociales>
            <perfil nombre = 'Linkedin'>https://www.linkedin.com/in/alberto-bolta-sanmateu-b43188306</perfil>
            <perfil nombre = 'Repositorio'>https://github.com/Lokhy87</perfil>
        </redes_sociales>
    </otros_datos>
    
    <formacion>
        <titulacion>
            <nombre>Licenciatura en Ciencias de la Actividad Fisica y el Deporte</nombre>
            <centro>Universidad Catolica de Valencia</centro>
            <fecha_inicio>
                <mes>Septiembre</mes> 
                <año>2005</año>
            </fecha_inicio>
            <fecha_finalizacion>
                <mes>Junio</mes> 
                <año>2010</año>
            </fecha_finalizacion>
        </titulacion>
        <titulacion>
            <nombre>Bootcamp Data Science</nombre>
            <centro>The Bridge</centro>
            <fecha_inicio>
                <mes>Febrero</mes> 
                <año>2024</año>
            </fecha_inicio>
            <fecha_finalizacion>
                <mes>Agosto</mes> 
                <año>2024</año>
            </fecha_finalizacion>
        </titulacion>
    </formacion>
    
    <idiomas>
        <idioma materno = 'true'>
            <nombre>Castellano</nombre>
            <expresion_oral>Alto</expresion_oral>
            <comprension_oral>Alto</comprension_oral>
            <expresion_escrita>Alto</expresion_escrita>
        </idioma>
        <idioma materno = 'false'>
            <nombre>Inglés</nombre>
            <expresion_oral>Medio</expresion_oral>
            <comprension_oral>Medio</comprension_oral>
            <expresion_escrita>Medio</expresion_escrita>
        </idioma>
        <idioma materno = 'true'>
            <nombre>Valenciano</nombre>
            <expresion_oral>Alto</expresion_oral>
            <comprension_oral>Alto</comprension_oral>
            <expresion_escrita>Medio</expresion_escrita>
        </idioma>
        <idioma materno = 'false'>
            <nombre>Italiano</nombre>
            <expresion_oral>Medio</expresion_oral>
            <comprension_oral>Medio</comprension_oral>
            <expresion_escrita>Medio</expresion_escrita>
        </idioma>
    </idiomas>
    
    <experiencia_laboral>
        <empresa>
            <nombre>Alfa Trainners</nombre>
            <puesto>Entrenador personal</puesto>
            <inicio_contrato>
                <dia>26</dia>
                <mes>Noviembre</mes> 
                <año>2023</año>
            </inicio_contrato>
            <final_contrato>
                <dia></dia>
                <mes></mes> 
                <año></año>
            </final_contrato>
        </empresa>
        <empresa>
            <nombre>TennisTrainer</nombre>
            <puesto>Preparador fisico y entrenador</puesto>
            <inicio_contrato>
                <dia>10</dia>
                <mes>Julio</mes> 
                <año>2013</año>
            </inicio_contrato>
            <final_contrato>
                <dia>1</dia>
                <mes>Junio</mes> 
                <año>2021</año>
            </final_contrato>
        </empresa>
    </experiencia_laboral>
    
    <competencias>
        <competencia>
            <nombre>Liderazgo</nombre>
            <nivel>2</nivel>
        </competencia>
        <competencia>
            <nombre>Trabajo en equipo</nombre>
            <nivel>5</nivel>
        </competencia>
        <competencia>
            <nombre>Iniciativa</nombre>
            <nivel>2</nivel>
        </competencia>
        <competencia>
            <nombre>Creatividad</nombre>
            <nivel>3</nivel>
        </competencia>
        <competencia>
            <nombre>Autonomía</nombre>
            <nivel>4</nivel>
        </competencia>
    </competencias>
    
    <datos_adicionales>
        <aficiones>
            <nombre>Deportes</nombre>
        </aficiones>
        <disponibilidad_viajar>Si</disponibilidad_viajar>
        <vehiculo_propio>Si</vehiculo_propio>
        <permisos>
            <nombre licencia = 'B1'>Coche</nombre>
            <nombre licencia = 'C'>Camion</nombre>
            <nombre licencia = 'C+E'>Trailer</nombre>
        </permisos>
    </datos_adicionales>
</curriculum>
