=== Lokhy87/DAW.FLORIDA/LMSGI - LENGUAJES DE MARCAS Y SISTEMAS DE GESTION DE LA INFORMACION/ACTIVIDADES/serie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="serie">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="fecha_estreno" type="xs:string" />
                <xs:element name="numero_temporadas" type="xs:string" />
                <xs:element name="genero" type="xs:string" />
                <xs:element name="actores">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="actor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="tipo" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="ppal" />
                                                        <xs:enumeration value="sec" />
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="director" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Lokhy87/DAW.FLORIDA/LMSGI - LENGUAJES DE MARCAS Y SISTEMAS DE GESTION DE LA INFORMACION/ACTIVIDADES/serie.xml
<?xml version="1.0" encoding="UTF-8"?>
<serie
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="serie.xsd">
    <nombre>Breaking Bad</nombre>
    <fecha_estreno>2008-04-11</fecha_estreno>
    <numero_temporadas>5</numero_temporadas>
    <genero>Drama</genero>
    <actores>
        <actor tipo="ppal">Bryan Cranston</actor>
        <actor tipo="ppal">Aaron Paul</actor>
        <actor tipo="ppal">Anna Gunn</actor>
        <actor tipo="ppal">Dean Norris</actor>
        <actor tipo="ppal">Betsy Brandt</actor>
        <actor tipo="sec">RJ Mitte</actor>
        <actor tipo="sec">Bob Odenkirk</actor>
        <actor tipo="sec">Giancarlo Esposito</actor>
        <actor tipo="sec">Jonathan Banks</actor>
        <actor tipo="sec">Laura Fraser</actor>
        <actor tipo="sec">Jesse Plemons</actor>
    </actores>
    <director>Vince Gilligan</director>
</serie>
